<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms>
<Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>MagicGarden</AssemblyName>
<PublishSingleFile>true</PublishSingleFile><SelfContained>true</SelfContained><RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>
<ItemGroup><ProjectReference Include="../MagicGarden.Windows.Core/MagicGarden.Windows.Core.csproj"/></ItemGroup>
</Project>